# Generated by Django 3.2 on 2024-02-24 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_superuser',
            field=models.IntegerField(blank=True, default=0, max_length=1),
        ),
    ]
