# Generated by Django 3.2 on 2024-03-03 11:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_alter_user_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True, validators=[django.core.validators.RegexValidator(code='invalid_slug', message='Enter a valid slug', regex='^[-a-zA-Z0-9_]+$')], verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='slug',
            field=models.SlugField(unique=True, validators=[django.core.validators.RegexValidator(code='invalid_slug', message='Enter a valid slug', regex='^[-a-zA-Z0-9_]+$')], verbose_name='Слаг'),
        ),
    ]
