# Generated by Django 3.2 on 2024-02-29 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_auto_20240229_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
